### ISSUE TITLE
RGB to hex problems 

### ISSUE THREAD

**Issue by Demonstrandum** [clichetouche/colour-converter#3]
When inputting any value below 16 in the RGB to hex I get a 'ZeroDivisionError', e.g. 
"python colour-converter.py 65 87 5" where green is 5 (5 < 16). 

Also, when giving the argument 'python colour-converter.py 255 n n'  I get a hex with #f0 .. .. instead of #ff .. ..

And last, giving an R,G or B value greater than 255 is allowed and since the converter is only made for two "digit" hexadecimal conversion gives a wrong answer as well as being allowed to exist since it is an invalid hex colour.

**Comment by clichetouche** [comment]
Thanks! Issues fixed [here](https://github.com/clichetouche/colour-converter/commit/4838c483f42ba68165c5158fa054a73459e8c655) and [here](https://github.com/clichetouche/colour-converter/commit/97deb5c06ae28fbb6dfb2fd49c1361f598cd9d11)
